name: Guild
main: cn.Guild
version: 1.0
author: key_q
commands:
   Guild:
      description: Guild basic command.
      usage: /<command> [player]
      permission: Guild.basic
      permission-message: You don't have <permission>
